### ISSUE TITLE
Unable to find the get_device implementation

### ISSUE THREAD

**Issue by pooji04** [muditbhargava66/PyxLSTM#13]
The example given in the README.md file had a import statement that said:

from xLSTM.utils import load_config, set_seed, get_device

I am unable to find the implementation for the get_device function, could you please clarify this?

**Comment by muditbhargava66** [comment]
All the files and dataset to run that example are not uploaded yet. The `get_device` function is not yet included in the `utils` directory as I'm still working on finalizing the codebase. I will push the complete implementation, including the missing function soon.

Best regards,
Mudit B.

**Comment by Strawl** [comment]
This is actually a duplicate of the same problem described here

https://github.com/muditbhargava66/PyxLSTM/issues/4

**Comment by muditbhargava66** [comment]
The issue has been definitively resolved in the latest update, Version 2.0.0.
