### ISSUE TITLE
Make embedding/vocab optional for timeseries data

### ISSUE THREAD

**Issue by nxfi777** [muditbhargava66/PyxLSTM#17]
Current implementation seems to require an embedding layer. This is inconvenient for models training on floating-point data.

**Comment by muditbhargava66** [comment]
Thanks for pointing this out! I understand the current implementation relies on an embedding layer, which might not be ideal for floating-point data. 
I'd love to assign this task to you - would you be willing to take on the task of modifying the implementation to accommodate floating-point data? If so, I can provide the necessary guidance and support. 
Let me know if you're interested and we can discuss further!
