### ISSUE TITLE
Is pip correct?

### ISSUE THREAD

**Issue by alifa98** [muditbhargava66/PyxLSTM#2]
Hi,

Sorry, but did you put the package on pip? cuz it seems we do no have such thing 😞 

I wanted to try this but:
```
ERROR: Could not find a version that satisfies the requirement PyxLSTM (from versions: none)
ERROR: No matching distribution found for PyxLSTM
```

**Comment by muditbhargava66** [comment]
Hi @alifa98,

Thanks for your interest in PyxLSTM! The package is not yet available on PyPI as I'm still finalizing the code. Once ready, I'll publish it to PyPI for easy installation via pip. Please follow the project's GitHub repo for updates on the release progress. Apologies for the inconvenience and let me know if you have any other questions.

Best,
Mudit B.
