### ISSUE TITLE
Problem with input gates in sLSTM

### ISSUE THREAD

**Issue by incllude** [muditbhargava66/PyxLSTM#22]
In the realization of sLSTM the cell state $c_t$ is updated like this:
```
c = f * c + i * lstm.weight_hh.new_zeros(batch_size, self.hidden_size)
``` 
So because of ```.new_zeros()``` input gate makes no sense

**Comment by muditbhargava66** [comment]
The issue has been definitively resolved in the latest update, Version 2.0.0.
