### ISSUE TITLE
A bug in mLSTM.py

### ISSUE THREAD

**Issue by CrazySpy** [muditbhargava66/PyxLSTM#3]
Hi,
I appreciate that you provided a good repo for my research.

But there is a bug in xLSTM/mLSTM.py. The variable 'i' in Line 59 is conflicting with the one in Line 65.

Best regards

**Comment by muditbhargava66** [comment]
The issue has been resolved in the latest code update, and I will be uploading it shortly.

**Comment by Paul-B98** [comment]
Hey @muditbhargava66, I would like to use this repo for my research too, is there any update regarding this and the other issues? would it be possible to share your plans or schedule on updating the code?
