### ISSUE TITLE
distinguish the index `i` and the output `i` of `i_gate` in sLSTM

### ISSUE THREAD

**Issue by Wang-Chbo** [muditbhargava66/PyxLSTM#4]
![image](https://github.com/muditbhargava66/PyxLSTM/assets/49528065/972f5ee4-1d10-45e0-9fcf-911da1ce99a4)

**Comment by Wang-Chbo** [comment]
distinguish the index i and the output i of i_gate in `sLSTM`

**Comment by muditbhargava66** [comment]
The updated code for this indexing issue will be available soon.

**Comment by antaoy** [comment]
![image](https://github.com/muditbhargava66/PyxLSTM/assets/33666323/a4dddf19-ded9-40ca-a6dc-6fad89f838cf)
i in the for loop is not separated from i in sLSTM, let's change the variable name.

**Comment by muditbhargava66** [comment]
The issue has been definitively resolved in the latest update, Version 2.0.0.
