### ISSUE TITLE
"setup.py" file doesn't exist

### ISSUE THREAD

**Issue by Rahul664** [muditbhargava66/PyxLSTM#6]
Manual installation fails as there is no "setup.py" file in the repo.

**Comment by muditbhargava66** [comment]
There is no `setup.py` file in the code base. The code can be built using the `pyproject.toml` file by running `python -m build`. The `README.md` file will be updated soon with other changes.

**Comment by mw66** [comment]
@Rahul664 you can just do:

```
$ pip install .
```

**Comment by jabowery** [comment]
The manual installation in the `README.md ` has still, after more than a month, not been corrected despite this issue being `closed`.
