### ISSUE TITLE
Please mention the dataset for the examples

### ISSUE THREAD

**Issue by baligar** [muditbhargava66/PyxLSTM#7]
Great job on the xLSTM repo, Mudit! It would be really helpful if you could include a sample dataset downloader to make running your examples easier.

**Comment by muditbhargava66** [comment]
I will update it soon. Thank you for your interest in the repository.

**Comment by WenhaoWa** [comment]
Thanks for your contribution.Before updation of dataset.Can I get the input shape and output shape information? Thank you
