### ISSUE TITLE
May be wrong code

### ISSUE THREAD

**Issue by pilgrimygy** [muditbhargava66/PyxLSTM#8]
https://github.com/muditbhargava66/PyxLSTM/blob/a34c2526aa2646203e6d512ed3186765bbd20b3b/xLSTM/mlstm.py#L89

This code will make a wrong in:
https://github.com/muditbhargava66/PyxLSTM/blob/a34c2526aa2646203e6d512ed3186765bbd20b3b/xLSTM/mlstm.py#L68

RuntimeError: The size of tensor a (2534) must match the size of tensor b (256) at non-singleton dimension 1

Can you please check it?

**Comment by liuzeyu6** [comment]
I also encountered this issue, which occurs when running the test_mlstm.py module.

**Comment by yangzhanpeng9** [comment]
I also encountered this bug

**Comment by muditbhargava66** [comment]
The issue has been definitively resolved in the latest update, Version 2.0.0.
